### ISSUE TITLE
Print model comments

### ISSUE THREAD

**Issue by aimmlegate** [frolovdev/anyspec#119]
Comments
How to handle comments

Construct and enhance ast
Enhance document node adding comments field array
Do same as in prettier
https://github.com/prettier/prettier/blob/4e46f92b8648c7f25de62bfaf4368aa3f2e588d9/src/language-graphql/parser-graphql.js#L6
Because we already skip comment tokens in the lookAhead method (hiding comment tokens for parser), we can just take the start token and iterate through a stream of tokens by hand and as a result, it gives us an array of comments

Compile
_get a start and end token when visiting and pop comments due to the first visit_

I think we should as much as possible simplify and copy prettier approach
https://github.com/prettier/prettier/blob/main/src/main/comments.js
They go through the comments token array and decorate each with .precedingNode, .enclosingNode, and/or .followingNode based on token location. And then they somehow use this information to print them

**Comment by frolovdev** [comment]
I recreate this task into models + comments

- [] print models with prettier
- [] print model comments with prettier
- [] add this into cli
- [] cli should support `check` flag as prettier does

**Comment by frolovdev** [comment]
I guess it can be closed because #138 was merged
